/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const DocumentInput = IDL.Record({
  'title' : IDL.Text,
  'content' : IDL.Text,
  'origin' : IDL.Text,
  'sellerName' : IDL.Text,
  'buyerName' : IDL.Text,
  'commodity' : IDL.Text,
  'docType' : IDL.Text,
});
export const Time = IDL.Int;
export const Document = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'ownerId' : IDL.Principal,
  'createdAt' : Time,
  'origin' : IDL.Text,
  'sellerName' : IDL.Text,
  'updatedAt' : Time,
  'buyerName' : IDL.Text,
  'commodity' : IDL.Text,
  'docType' : IDL.Text,
});
export const UserDto = IDL.Record({ 'id' : IDL.Principal, 'name' : IDL.Text });
export const UserProfile = IDL.Record({
  'id' : IDL.Principal,
  'name' : IDL.Text,
  'createdAt' : Time,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createDocument' : IDL.Func([DocumentInput], [IDL.Text], []),
  'deleteDocument' : IDL.Func([IDL.Text], [], []),
  'getAllDocuments' : IDL.Func([], [IDL.Vec(Document)], ['query']),
  'getAllUsers' : IDL.Func([], [IDL.Vec(UserDto)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDocument' : IDL.Func([IDL.Text], [Document], ['query']),
  'getUserProfile' : IDL.Func([IDL.Principal], [UserProfile], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listUserDocuments' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(Document)],
      ['query'],
    ),
  'saveCallerUserProfile' : IDL.Func([IDL.Text], [], []),
  'searchDocumentsByField' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Vec(Document)],
      ['query'],
    ),
  'updateDocument' : IDL.Func([IDL.Text, DocumentInput], [], []),
  'updateUserName' : IDL.Func([IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const DocumentInput = IDL.Record({
    'title' : IDL.Text,
    'content' : IDL.Text,
    'origin' : IDL.Text,
    'sellerName' : IDL.Text,
    'buyerName' : IDL.Text,
    'commodity' : IDL.Text,
    'docType' : IDL.Text,
  });
  const Time = IDL.Int;
  const Document = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'ownerId' : IDL.Principal,
    'createdAt' : Time,
    'origin' : IDL.Text,
    'sellerName' : IDL.Text,
    'updatedAt' : Time,
    'buyerName' : IDL.Text,
    'commodity' : IDL.Text,
    'docType' : IDL.Text,
  });
  const UserDto = IDL.Record({ 'id' : IDL.Principal, 'name' : IDL.Text });
  const UserProfile = IDL.Record({
    'id' : IDL.Principal,
    'name' : IDL.Text,
    'createdAt' : Time,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createDocument' : IDL.Func([DocumentInput], [IDL.Text], []),
    'deleteDocument' : IDL.Func([IDL.Text], [], []),
    'getAllDocuments' : IDL.Func([], [IDL.Vec(Document)], ['query']),
    'getAllUsers' : IDL.Func([], [IDL.Vec(UserDto)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDocument' : IDL.Func([IDL.Text], [Document], ['query']),
    'getUserProfile' : IDL.Func([IDL.Principal], [UserProfile], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listUserDocuments' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(Document)],
        ['query'],
      ),
    'saveCallerUserProfile' : IDL.Func([IDL.Text], [], []),
    'searchDocumentsByField' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Vec(Document)],
        ['query'],
      ),
    'updateDocument' : IDL.Func([IDL.Text, DocumentInput], [], []),
    'updateUserName' : IDL.Func([IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };