/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Document {
  'id' : string,
  'title' : string,
  'content' : string,
  'ownerId' : Principal,
  'createdAt' : Time,
  'origin' : string,
  'sellerName' : string,
  'updatedAt' : Time,
  'buyerName' : string,
  'commodity' : string,
  'docType' : string,
}
export interface DocumentInput {
  'title' : string,
  'content' : string,
  'origin' : string,
  'sellerName' : string,
  'buyerName' : string,
  'commodity' : string,
  'docType' : string,
}
export type Time = bigint;
export interface UserDto { 'id' : Principal, 'name' : string }
export interface UserProfile {
  'id' : Principal,
  'name' : string,
  'createdAt' : Time,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createDocument' : ActorMethod<[DocumentInput], string>,
  'deleteDocument' : ActorMethod<[string], undefined>,
  'getAllDocuments' : ActorMethod<[], Array<Document>>,
  'getAllUsers' : ActorMethod<[], Array<UserDto>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getDocument' : ActorMethod<[string], Document>,
  'getUserProfile' : ActorMethod<[Principal], UserProfile>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listUserDocuments' : ActorMethod<[Principal], Array<Document>>,
  'saveCallerUserProfile' : ActorMethod<[string], undefined>,
  'searchDocumentsByField' : ActorMethod<[string, string], Array<Document>>,
  'updateDocument' : ActorMethod<[string, DocumentInput], undefined>,
  'updateUserName' : ActorMethod<[string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];